export const groups = [
  {
    label: "Cloud",
    tags: [
      { label: "AWS",          key: "aws" },
      { label: "Azure",        key: "azure" },
      { label: "DigitalOcean", key: "digitalocean" },
      { label: "Cloudflare",   key: "cloudflare" },
      { label: "Oracle Cloud", key: "oracle" },
    ],
  },
  {
    label: "Cloud Services",
    tags: [
      // AWS Compute & Networking
      { label: "EC2",          key: "amazonec2" },
      { label: "EKS",          key: "amazoneks" },
      { label: "VPC",          key: "amazonvpc" },
      { label: "NLB",          key: "awsnlb" },
      { label: "NAT Gateway",  key: "awsnatgateway" },
      { label: "CloudFront",   key: "amazoncloudfront" },
      { label: "Route 53",     key: "amazonroute53" },
      { label: "WAF",          key: "awswaf" },
      // AWS Storage & Data
      { label: "S3",           key: "amazons3" },
      { label: "RDS",          key: "amazonrds" },
      { label: "DynamoDB",     key: "amazondynamodb" },
      // AWS Security
      { label: "IAM",          key: "awsiam" },
      { label: "KMS",          key: "awskms" },
      { label: "GuardDuty",    key: "amazonguardduty" },
      { label: "CloudTrail",   key: "awscloudtrail" },
      { label: "Security Hub", key: "awssecurityhub" },
      { label: "AWS Config",   key: "awsconfig" },
      { label: "Organizations",key: "awsorganizations" },
      // AWS Observability
      { label: "CloudWatch",   key: "amazoncloudwatch" },
      { label: "EventBridge",  key: "amazoneventbridge" },
      { label: "SNS",          key: "amazonsns" },
      // Azure
      { label: "AKS",          key: "azureaks" },
      { label: "ACR",          key: "azureacr" },
      { label: "Key Vault",    key: "azurekeyvault" },
      { label: "VNet",         key: "azurevnet" },
      { label: "Azure VM",     key: "azurevm" },
      // OCI
      { label: "OCI Compute",  key: "ocicompute" },
      { label: "OCI VCN",      key: "ocivcn" },
      { label: "OpenVPN",      key: "openvpn" },
    ],
  },
  {
    label: "Full-Stack",
    tags: [
      { label: "React",        key: "react" },
      { label: "Next.js",      key: "nextdotjs" },
      { label: "Vue.js",       key: "vuedotjs" },
      { label: "Nuxt",         key: "nuxt" },
      { label: "JavaScript",   key: "javascript" },
      { label: "TypeScript",   key: "typescript" },
      { label: "Node.js",      key: "nodedotjs" },
      { label: "Express",      key: "express" },
      { label: "GraphQL",      key: "graphql" },
      { label: "Python",       key: "python" },
      { label: "Django",       key: "django" },
      { label: "PostgreSQL",   key: "postgresql" },
      { label: "Redis",        key: "redis" },
      { label: "MongoDB",      key: "mongodb" },
      { label: "Stripe",       key: "stripe" },
      { label: "Firebase",     key: "firebase" },
      { label: "Tailwind CSS", key: "tailwindcss" },
    ],
  },
  {
    label: "DevOps",
    tags: [
      { label: "Docker",          key: "docker" },
      { label: "Kubernetes",      key: "kubernetes" },
      { label: "GitHub Actions",  key: "githubactions" },
      { label: "ArgoCD",          key: "argo" },
      { label: "Helm",            key: "helm" },
      { label: "Kustomize",       key: "kustomize" },
      { label: "Terraform",       key: "terraform" },
      { label: "Ansible",         key: "ansible" },
      { label: "Kyverno",         key: "kyverno" },
      { label: "Cosign",          key: "cosign" },
      { label: "Trivy",           key: "trivy" },
      { label: "Falco",           key: "falco" },
      { label: "OPA",             key: "openpolicyagent" },
      { label: "Prometheus",      key: "prometheus" },
      { label: "Grafana",         key: "grafana" },
      { label: "Jaeger",          key: "jaeger" },
      { label: "Sentry",          key: "sentry" },
    ],
  },
];
