// projects data — separated for maintainability
export const coreProjects = [
  {
    slug: "kubernetes-platform",
    niche: "Cloud Native",
    tag: "Infrastructure · Cloud Native · Multi-Cloud",
    title: "Production-Grade Kubernetes Platform",
    techs: ["kubernetes", "terraform", "aws", "azure", "digitalocean", "istio", "argo", "prometheus", "grafana", "falco", "trivy", "calico", "jaeger", "velero", "docker", "githubactions", "helm"],
    subtitle: "AWS · Azure · DigitalOcean · Self-Managed · HA Cluster · Built from Scratch",
    github: "https://github.com/artariq-dev/self-managed-k8s-aws",
    githubLabel: "AWS",
    githubAlt: { label: "Azure / DigitalOcean", url: "https://github.com/artariq-dev/hipster-shop" },
    source: { text: "Orchestrated 12 microservices based on Google's project: ", link: "Online Boutique", url: "https://github.com/GoogleCloudPlatform/microservices-demo" },
    diagram: `${process.env.PUBLIC_URL}/projects/k8s-platform/architecture.svg`,
    problem: "When your cloud provider manages Kubernetes, you lose control over security, performance, and cost. If something breaks, you're debugging a black box — and every hour of downtime costs you money and trust.",
    solution: "Built self-managed Kubernetes clusters from raw compute across three cloud providers — giving full ownership of every layer with zero reliance on a managed control plane. The result: a portable, auditable platform that runs identically on AWS, Azure, or DigitalOcean.",
    implementation: [
      "Terraform provisions all cloud infrastructure end-to-end.",
      "kubeadm bootstraps the control plane and worker nodes.",
      "Google's 12-microservice Online Boutique runs as the production workload.",
      "Istio enforces mTLS across all service-to-service communication.",
      "ArgoCD drives GitOps deployments.",
      "Falco and Trivy handle runtime and image security.",
      "Prometheus and Grafana provide monitoring dashboards and alerting.",
      "Calico CNI enables pod networking with network policies.",
      "cert-manager automates TLS certificate provisioning for ingress.",
      "Loki and Promtail centralize log collection and querying.",
      "HPA and VPA handle automatic horizontal and vertical pod scaling.",
      "Jaeger provides end-to-end distributed tracing across services.",
      "Velero manages cluster backups and disaster recovery.",
    ],
    impact: "Identical platform running on three cloud providers — proving full portability with zero vendor lock-in. 43 AWS resources provisioned with zero manual steps. 11 of 12 engineering phases complete including service mesh, autoscaling, distributed tracing, and GitOps delivery.",
    stats: [
      { value: "3", label: "Clouds, One Platform", sub: "AWS · Azure · DigitalOcean" },
      { value: "100%", label: "Control Plane Ownership", sub: "No managed black box" },
      { value: "43", label: "Resources, Zero Clicks", sub: "Terraform end-to-end" },
      { value: "12", label: "Services in Production", sub: "Full observability stack" },
    ],
  },
  {
    slug: "aws-secure-baseline",
    niche: "Security & Compliance",
    tag: "AWS · Security · Infrastructure-as-Code · Multi-Account",
    title: "AWS Secure Baseline — Multi-Account Security Platform",
    techs: ["amazonwebservices", "terraform", "githubactions", "cloudflare", "kustomize"],
    subtitle: "GuardDuty · Security Hub · CloudTrail · AWS Config · SCPs · Terraform · GitHub Actions",
    github: "https://github.com/artariq-dev/aws-secure-baseline",
    diagram: `${process.env.PUBLIC_URL}/projects/aws-secure-baseline/architecture.svg`,
    problem: "Most AWS environments treat security as an afterthought — enabled in prod but not dev, alerts that nobody checks, and nothing preventing an admin from disabling protections entirely. By the time you fix it, every environment has drifted into a different, un-auditable state.",
    solution: "Built a Terraform-based security platform that provisions the same baseline across every AWS environment on day one — enforced at the organisation level so even an admin with compromised credentials can't disable it. Detection, alerting, and compliance checks run identically everywhere, automatically.",
    implementation: [
      "Two isolated AWS accounts: non-prod (dev/sit) and prod (staging/prod) — blast radius contained by design.",
      "CloudTrail with multi-region logging, S3 data events, Lambda invocations, log file validation, and 9 CIS-aligned CloudWatch alarms for root usage, IAM changes, and security group modifications.",
      "GuardDuty with S3 Protection, Kubernetes Protection, and Malware Protection — HIGH/CRITICAL findings routed to SNS via EventBridge within minutes.",
      "Security Hub running CIS AWS Foundations Benchmark v1.4.0 and AWS Foundational Security Best Practices across all regions, with a finding aggregator for a single-pane view.",
      "30 AWS Config managed rules covering encryption, access control, logging, networking, and compute — non-compliance events trigger SNS alerts automatically.",
      "6 SCPs enforced at the OU level: deny leaving the organisation, deny disabling security services, deny root account usage, restrict to approved regions, block public S3, and require IMDSv2 on all EC2.",
      "GitHub Actions CI/CD via OIDC — no stored credentials. Plan on PR, apply on merge, manual approval gate for prod. tfsec + checkov block HIGH/CRITICAL findings before merge.",
      "KMS manages per-service encryption keys with automatic rotation.",
      "S3 and DynamoDB provide remote Terraform state with state locking.",
      "CloudFront and WAF secure the global DNS endpoint.",
      "OIDC IAM roles connect GitHub Actions to AWS without stored credentials.",
    ],
    impact: "Every environment gets an identical, auditable security baseline from day one — no manual steps, no drift. Security cannot be disabled even by a compromised admin account. Threats are detected in real-time across behavioural anomalies, configuration drift, compliance gaps, and active threats simultaneously.",
    stats: [
      { value: "6", label: "SCPs, Zero Overrides", sub: "Enforced above IAM" },
      { value: "30", label: "Config Rules", sub: "Encryption · IAM · Network · Compute" },
      { value: "9", label: "CIS Alarms", sub: "Real-time on critical API calls" },
      { value: "4", label: "Environments, One Baseline", sub: "dev · sit · staging · prod" },
    ],
  },
  {
    slug: "secure-supply-chain",
    niche: "Supply Chain Security",
    tag: "Supply Chain Security · GitOps · Platform Engineering",
    title: "End-to-End Secure Software Supply Chain",
    techs: ["go", "docker", "githubactions", "argo", "kubernetes", "kustomize", "falco", "trivy", "cosign", "kyverno"],
    subtitle: "Cosign Keyless · SLSA L2 · Kyverno · Falco · ArgoCD · SBOM · Distroless",
    github: "https://github.com/artariq-dev/secure-supply-chain",
    diagram: `${process.env.PUBLIC_URL}/projects/secure-supply-chain/architecture.svg`,
    problem: "You can't prove that what's running in production is exactly what was built and approved. A tampered image can slip through a standard pipeline — and you'd have no way to know until it's too late.",
    solution: "Designed a three-layer enforcement chain: every artifact is signed the moment it's built, verified before it's deployed, and monitored while it runs. No signing keys to manage — OIDC handles authentication automatically. If an image isn't signed, it never reaches a running pod.",
    implementation: [
      "Multi-stage distroless build compiles the Go application into a minimal runtime image.",
      "GitHub Actions CI executes dual vulnerability scanning (Trivy + Grype).",
      "Syft generates an SBOM, attested to the image via Cosign.",
      "Cosign keyless signing using OIDC — no signing keys to store, rotate, or leak.",
      "The SLSA GitHub Generator produces L2 provenance using an isolated signing job.",
      "The digest is pinned in the GitOps repository — no mutable tags allowed.",
      "ArgoCD syncs exclusively from the pinned digest via Kustomize.",
      "Kyverno verifyImages policy enforces all three attestations at admission time before any pod is scheduled.",
      "Falco runtime rules monitor pod behaviour for anomalies and policy violations.",
      "PSS Restricted enforcement and no :latest tag policy ensure production readiness.",
    ],
    impact: "Every piece of code is cryptographically traceable from the commit that wrote it to the pod running it. Zero unsigned images make it to production. Zero signing keys to store, rotate, or leak — OIDC eliminates key management entirely.",
    stats: [
      { value: "3", label: "Enforcement Layers", sub: "Nothing slips through" },
      { value: "0", label: "Stored Signing Keys", sub: "Keyless OIDC only" },
      { value: "0", label: "Mutable Tags in Prod", sub: "Digest-pinned, always" },
      { value: "SLSA L2", label: "Provenance on Every Build", sub: "Commit → pod, traceable" },
    ],
  },
  {
    slug: "azure-opa-pipeline",
    niche: "Policy-as-Code",
    tag: "Azure · DevOps · Policy-as-Code",
    title: "Azure DevOps Pipeline with OPA Policy Enforcement",
    techs: ["microsoftazure", "terraform", "githubactions", "ansible", "openpolicyagent", "docker", "nginx", "kubernetes", "trivy"],
    subtitle: "AKS · ACR · GitHub Actions · Ansible · Open Policy Agent",
    github: "https://github.com/artariq-dev/Portfolio-Devops",
    diagram: `${process.env.PUBLIC_URL}/projects/portfolio-devops/architecture.svg`,
    problem: "Bad configurations — open access, missing encryption, untagged resources — reach production before anyone notices. Manual reviews don't catch everything and don't scale. By the time you find the problem, it's already costing you.",
    solution: "Wrote policy-as-code rules that evaluate every infrastructure change before it's applied — blocking non-compliant configurations at the source. Four parallel pipelines (infrastructure, app, config, security) execute from a single git push with zero manual gates.",
    implementation: [
      "Terraform provisions AKS, ACR, Key Vault, and VNet on Azure.",
      "OPA policies enforce no-public-AKS and mandatory resource tagging at plan time — violations fail the pipeline before apply.",
      "Docker multi-stage build packages the Nginx application.",
      "Image is pushed to Azure Container Registry.",
      "AKS deployment applies the configured workload to the cluster.",
      "Ansible configures the bastion host post-provisioning.",
      "GitHub Actions orchestrates all four pipelines in parallel.",
      "The security pipeline runs Trivy image scanning independently.",
      "Node Exporter monitoring tracks bastion host metrics.",
    ],
    impact: "Zero non-compliant resources reach production. Violations caught at plan time, not after deployment. Four parallel pipelines cut delivery time. Zero manual steps from commit to running on AKS.",
    stats: [
      { value: "0", label: "Bad Configs Reach Azure", sub: "Blocked at plan time" },
      { value: "4", label: "Pipelines, One Git Push", sub: "Infra · App · Config · Security" },
      { value: "5", label: "Azure Services Wired Up", sub: "AKS · ACR · KV · VNet · VM" },
      { value: "0", label: "Manual Steps", sub: "Commit to running workload" },
    ],
  },
  {
    slug: "gitops-sealed-secrets",
    niche: "GitOps & Security",
    tag: "Azure · GitOps · Secret Management",
    title: "Multi-Environment GitOps Platform with Sealed Secrets",
    techs: ["microsoftazure", "terraform", "argo", "helm", "kubernetes", "kustomize", "docker", "trivy", "k3s", "githubactions"],
    subtitle: "K3s on Azure · ArgoCD · Helm · Sealed Secrets · Dev/Staging/Prod",
    github: "https://github.com/artariq-dev/DevSecOps-Platform",
    diagram: `${process.env.PUBLIC_URL}/projects/devsecops-platform/architecture.svg`,
    problem: "Storing passwords and API keys in Git is a security risk. Leaving them out breaks the GitOps model where everything should be version-controlled and auditable. Most teams accept the tradeoff — I found a way to get both.",
    solution: "Implemented Sealed Secrets — secrets are encrypted before they ever touch Git, and only the in-cluster controller holds the decryption key. Plaintext credentials never exist outside the cluster boundary, while the full GitOps model (version control, audit trail, auto-sync) is preserved end-to-end.",
    implementation: [
      "Terraform provisions a K3s VM on Azure.",
      "ArgoCD is installed and configured for GitOps delivery.",
      "Sealed Secrets encrypts credentials before they ever touch Git.",
      "A Helm chart packages the application for consistent cross-environment deployments.",
      "Dev overlay configured with Kustomize for namespace isolation.",
      "Staging overlay mirrors production configuration for pre-release validation.",
      "Prod overlay enforces stricter RBAC and resource limits.",
      "CI pipeline builds and scans images with Trivy before pushing to Docker Hub.",
      "ArgoCD manages three environment overlays (dev/staging/prod) via Kustomize — each isolated by namespace and RBAC.",
      "Every environment self-heals — configuration drift is eliminated entirely.",
    ],
    impact: "Zero plaintext secrets in Git. Three fully isolated environments managed from a single repository with automatic sync and self-healing — configuration drift is eliminated entirely.",
    stats: [
      { value: "0", label: "Plaintext Secrets in Git", sub: "Encrypted before commit" },
      { value: "3", label: "Environments, One Repo", sub: "dev · staging · prod" },
      { value: "0", label: "Config Drift", sub: "ArgoCD self-heals always" },
      { value: "100%", label: "GitOps Model Preserved", sub: "Security + auditability" },
    ],
  },
  {
    slug: "agency-021",
    niche: "Full-Stack CMS",
    tag: "Full Stack · Nuxt 3 · Strapi CMS · Cloudflare",
    title: "021 — Agency Website with Strapi CMS",
    techs: ["nuxt", "strapi", "cloudflare", "tailwindcss", "cloudflareworkers"],
    subtitle: "Headless CMS · Blog System · Calendly · EmailOctopus · Cloudflare Workers",
    live: "https://021.uk/",
    images: [
      `${process.env.PUBLIC_URL}/projects/021/01.webp`,
      `${process.env.PUBLIC_URL}/projects/021/02.webp`,
      `${process.env.PUBLIC_URL}/projects/021/03.webp`,
      `${process.env.PUBLIC_URL}/projects/021/04.webp`,
    ],
    problem: "The agency needed a marketing site where content editors could manage blog posts and pages without developer involvement — but most CMS solutions are either too rigid or too complex for a small team.",
    solution: "Built a headless CMS architecture with Strapi where editors write content in markdown, and the site renders it server-side with dynamic slug routing. Newsletter signups flow through EmailOctopus API, and the entire site is deployed on Cloudflare Workers for global performance.",
    impact: "Content editors manage posts and pages independently with zero developer hand-holding. The site loads fast globally via Cloudflare's edge network, and the headless architecture means the frontend can be swapped without touching the CMS.",
    implementation: [
      "Strapi CMS set up with custom content types for pages and blog posts.",
      "Nuxt 3 renders markdown content server-side with dynamic slug routing.",
      "EmailOctopus API handles newsletter subscriptions.",
      "Calendly embedded for call scheduling.",
      "Deployed on Cloudflare Workers via Wrangler CLI.",
      "Tailwind CSS provides utility-first styling across the site.",
    ],
    stats: [],
  },
  {
    slug: "agency-kitchenz",
    niche: "Full-Stack E-Commerce",
    tag: "Full Stack · Nuxt.js · Vue.js · UnoCSS",
    title: "Kitchenz — Product Configurator",
    techs: ["nuxt", "vuedotjs", "unocss"],
    subtitle: "Interactive product configurator — Nuxt.js · Vue.js · UnoCSS · SSG",
    live: "https://www.kitchenz.de/",
    images: [
      `${process.env.PUBLIC_URL}/projects/kitchenz/01.webp`,
      `${process.env.PUBLIC_URL}/projects/kitchenz/02.webp`,
      `${process.env.PUBLIC_URL}/projects/kitchenz/03.webp`,
      `${process.env.PUBLIC_URL}/projects/kitchenz/04.webp`,
    ],
    problem: "Customers needed a way to customise kitchen configurations, materials, and components before purchase — but the existing site offered only static product pages with no interactivity.",
    solution: "Built an interactive product configurator that lets users customise kitchen layouts, choose materials, and see real-time visual feedback. Built with Nuxt.js and Vue.js for smooth interactivity, with UnoCSS for rapid styling.",
    impact: "Customers can explore and customise kitchen configurations before reaching out — reducing friction in the sales process and giving them confidence in their choices.",
    implementation: [
      "Nuxt.js with static site generation for fast initial load.",
      "Vue.js interactive configurator with real-time state management.",
      "UnoCSS for utility-first styling without heavy CSS bundles.",
      "Open Graph meta tags for social sharing.",
    ],
    stats: [],
  },
  {
    slug: "agency-papierfischer",
    niche: "Full-Stack Storefront",
    tag: "Full Stack · Headless Commerce · Magento 2",
    title: "PaperFisher — Magento 2 Storefront",
    techs: ["magento", "graphql", "nuxt", "vuedotjs"],
    subtitle: "Headless Commerce · Magento 2 GraphQL · Nuxt 2 · Vue Storefront 2",
    live: "https://www.papierfischer.de/",
    images: [
      `${process.env.PUBLIC_URL}/projects/papierfischer/01.webp`,
      `${process.env.PUBLIC_URL}/projects/papierfischer/02.webp`,
      `${process.env.PUBLIC_URL}/projects/papierfischer/03.webp`,
      `${process.env.PUBLIC_URL}/projects/papierfischer/04.webp`,
    ],
    problem: "The existing Magento 2 storefront had slow category pages with no pagination, price sorting, or alphabetical sorting — making it hard for users to browse products efficiently.",
    solution: "Built a headless storefront using Vue Storefront 2 with Nuxt 2, connected to Magento 2 via GraphQL. Added pagination, price sorting, and alphabetical sorting to category pages — dramatically improving the browsing experience.",
    impact: "Customers can now browse products by price or alphabetically, with paginated results that load fast. The headless architecture decouples the frontend from Magento, making future updates easier.",
    implementation: [
      "Vue Storefront 2 connected to Magento 2 via GraphQL API.",
      "Nuxt 2 for server-side rendering and static generation.",
      "Pinia for state management across the storefront.",
      "nuxt-i18n for multi-language support.",
      "Custom sorting and pagination components on category pages.",
    ],
    stats: [],
  },
  {
    slug: "agency-birdie",
    niche: "Full-Stack SaaS",
    tag: "Full Stack · Nuxt 3 · Firebase · Stripe",
    title: "Birdie — Shopify Agency SaaS Landing Page",
    techs: ["nuxt", "firebase", "stripe", "tailwindcss", "vuedotjs"],
    subtitle: "Stripe Subscriptions · Firebase Firestore · EN/DE i18n · Conversion-Optimised",
    live: "https://www.birdiecommerce.com/",
    dribbble: "https://dribbble.com/shots/27096097-BIRDIE-SHOPIFY-WEB-AGENCY",
    images: [
      `${process.env.PUBLIC_URL}/projects/birdie/01.webp`,
      `${process.env.PUBLIC_URL}/projects/birdie/02.webp`,
      `${process.env.PUBLIC_URL}/projects/birdie/03.webp`,
    ],
    problem: "The agency needed a bilingual (EN/DE) marketing site that could capture leads and handle subscription purchases — without complex backend infrastructure.",
    solution: "Built a Nuxt 3 marketing site with Firebase Firestore for lead capture, Stripe server-side checkout for subscription payments, and full vue-i18n internationalisation for English and German. The site is conversion-optimised with clear CTAs and minimal friction.",
    impact: "Visitors can sign up in either language, submit leads directly to Firestore, and purchase subscriptions through Stripe — all without a custom backend. The site converts visitors into paying clients with a streamlined flow.",
    implementation: [
      "Nuxt 3 frontend with Tailwind CSS and Headless UI components.",
      "Firebase Firestore stores lead intake form submissions.",
      "Stripe server-side checkout handles subscription purchases securely.",
      "vue-i18n provides full EN/DE internationalisation.",
      "Deployed and hosted with automated CI/CD.",
    ],
    stats: [],
  },
  {
    slug: "find24",
    niche: "Full-Stack SaaS",
    tag: "Full Stack · Nuxt 3 · Algolia · Mapbox",
    title: "Find-24 — Local Service Provider Marketplace",
    techs: ["nuxt", "vuedotjs", "typescript", "tailwindcss", "algolia", "mapbox"],
    subtitle: "Algolia Search · Mapbox Geolocation · Pinia · 180+ Providers · 600+ Clients",
    github: "https://github.com/artariq-dev/Find-24",
    images: [
      `${process.env.PUBLIC_URL}/projects/find24/01.webp`,
      `${process.env.PUBLIC_URL}/projects/find24/02.webp`,
      `${process.env.PUBLIC_URL}/projects/find24/03.webp`,
      `${process.env.PUBLIC_URL}/projects/find24/04.webp`,
      `${process.env.PUBLIC_URL}/projects/find24/05.webp`,
    ],
    problem: "Finding a reliable local service provider — plumber, mechanic, cleaner, electrician — is slow and trust-deficient. Customers waste time calling around with no way to compare ratings, pricing, or availability.",
    solution: "Built a full-stack marketplace with Algolia-powered instant search, Mapbox geolocation, and filter-by-category/price/rating. Users find and connect with verified providers in minutes. Separate dashboards for users and providers keep both sides of the marketplace engaged.",
    impact: "180+ service providers onboarded. 600+ satisfied clients. Users can search, filter, view on a map, and connect with a provider in under 3 steps.",
    implementation: [
      "Algolia InstantSearch powers real-time provider search with category, price range, and rating filters.",
      "Mapbox integration renders providers on a map with location autocomplete.",
      "User dashboard: service requests, booking history, spending stats, notifications.",
      "Provider dashboard: bookings, completed services, earnings overview.",
      "Multi-step provider signup flow: profile, services, categories, experience, photo upload.",
      "Auth: email/password, Google OAuth, Facebook OAuth, email verification, forgot/reset password.",
      "TypeScript throughout — typed API responses, user, service, and category models.",
      "Pinia stores for user state, services, and auth.",
      "PM2 for production process management.",
      "Mobile-responsive search with dedicated mobile filter components.",
    ],
    stats: [
      { value: "180+", label: "Service Providers", sub: "Plumbers · Mechanics · Cleaners · More" },
      { value: "600+", label: "Satisfied Clients", sub: "Verified connections" },
      { value: "3", label: "Steps to Hire", sub: "Sign up → Select → Connect" },
    ],
  },
  {
    slug: "yearpeek",
    niche: "Full-Stack SaaS",
    tag: "Full Stack · Nuxt 3 · Vue 3 · SaaS",
    title: "YearPeek — Yearly Calendar Management SaaS",
    techs: ["nuxt", "vuedotjs", "typescript", "tailwindcss"],
    subtitle: "Full-Year View · Multi-Calendar · Event & Task Management · Guest Invites · Google Auth",
    github: "https://github.com/artariq-dev/calendar-frontend",
    dribbble: "https://dribbble.com/shots/25508905-YEARPEEK-Annual-Calendar",
    images: [
      `${process.env.PUBLIC_URL}/projects/yearpeek/01.webp`,
      `${process.env.PUBLIC_URL}/projects/yearpeek/02.webp`,
      `${process.env.PUBLIC_URL}/projects/yearpeek/03.webp`,
      `${process.env.PUBLIC_URL}/projects/yearpeek/04.webp`,
      `${process.env.PUBLIC_URL}/projects/yearpeek/05.webp`,
      `${process.env.PUBLIC_URL}/projects/yearpeek/06.webp`,
    ],
    problem: "Most calendars force you to scroll through week after week, juggling separate apps for work and personal schedules. There's no way to see the full year at once or manage everything in one place.",
    solution: "Built a SaaS calendar platform that renders the entire year on one screen — no scrolling, no zooming. Multiple calendars (personal, work, shared) live side by side. Events and tasks are created, edited, and viewed from a clean sidebar without leaving the year view.",
    impact: "Users see their entire year at a glance and manage all calendars in one place — reducing context-switching and missed events.",
    implementation: [
      "Full-year main calendar view with all events and tasks rendered across 12 months simultaneously.",
      "Week calendar view for daily detail when needed.",
      "Event CRUD: title, date, time, location, video meeting link, guests, reminders.",
      "Task CRUD with checkbox completion tracking.",
      "Multiple calendars per user — create, colour-code, show/hide independently.",
      "Calendar sharing — search users and invite them to shared calendars.",
      "Guest management on events with invite flow.",
      "Google Auth integration for one-click sign-in.",
      "Nuxt server API layer (17 BFF endpoints) proxying to backend.",
      "Pinia stores for modal state and profile/calendar configuration.",
      "Profile management with picture upload.",
      "Settings: general, notifications, calendars, profile.",
      "Third-party schedule sync support.",
    ],
    stats: [],
  },
  {
    slug: "django-clinical-crm",
    niche: "Cloud Native",
    tag: "Full Stack · Django · CRM · AdTech",
    title: "CRM for Clinical Appointments + Location-Based Ad Targeting",
    images: [
      `${process.env.PUBLIC_URL}/projects/django-clinical-crm/01.webp`,
      `${process.env.PUBLIC_URL}/projects/django-clinical-crm/02.webp`,
      `${process.env.PUBLIC_URL}/projects/django-clinical-crm/03.webp`,
      `${process.env.PUBLIC_URL}/projects/django-clinical-crm/04.webp`,
    ],
    diagram: `${process.env.PUBLIC_URL}/projects/django-clinical-crm/architecture.svg`,
    techs: ["django", "python", "postgresql", "redis", "docker", "githubactions", "celery", "googleads", "facebook", "aws"],
    subtitle: "Django · PostgreSQL/PostGIS · Celery · Redis · Docker · GitHub Actions",
    problem: "When you rely on disconnected tools — spreadsheets, phone scheduling, guesswork ad spending — you lose control over patient data, appointment flow, and marketing ROI. Every missed appointment costs you revenue and patient trust.",
    solution: "Built a complete clinical CRM on Django with PostgreSQL/PostGIS for geographic queries and Celery + Redis for background job processing. Heatmap analytics reveal high-performing areas, enabling data-driven Google/Meta ad campaigns with measurable results: 38% lower CPA, 68% better ROAS.",
    impact: "Production-ready clinical CRM with full appointment system, geographic analytics, and data-driven ad campaigns — delivering 38% lower CPA and 68% better ROAS.",
    implementation: [
      "CSV bulk import loads 5,000+ patient records with zero manual data entry.",
      "Django Contact model captures patient details: name, email, phone, address, city, state, postcode, country.",
      "Cases/Tickets system repurposed as appointment scheduling with status tracking and doctor assignment.",
      "LocationTracking model records geolocation, area, postal code, and conversion status per appointment.",
      "PostgreSQL + PostGIS enables geographic queries and proximity analysis.",
      "Django REST API provides endpoints for all CRUD operations across contacts, appointments, and analytics.",
      "Celery + Redis handle background jobs: email notifications and reminders.",
      "Plotly/Mapbox heatmap displays appointment density and conversion rates by geographic area — powered by patient geolocation, postal code, and appointment outcome data.",
      "Heatmap insights used to run targeted ad campaigns on Google/Meta Ads with measurable ROI.",
      "ConversionAnalytics model aggregates appointments, conversion rate, CPA, and revenue by area.",
      "Mailgun delivers appointment notifications, follow-ups, and weekly performance reports.",
      "GitHub Actions CI/CD pipeline runs tests and deploys changes automatically.",
      "Docker containerization ensures identical environments across dev, staging, and production.",
      "Multi-clinic support via multi-tenant architecture — scale from 1 clinic to 100+.",
      "Git-based infrastructure as code — entire system reproducible from GitHub with single deploy command.",
    ],
    stats: [
      { value: "38%", label: "Lower CPA", sub: "Data-driven ad optimization" },
      { value: "68%", label: "Better ROAS", sub: "2.5x → 4.2x in 60 days" },
      { value: "40-50%", label: "Fewer No-Shows", sub: "Automated reminders" },
      { value: "99.5%", label: "System Uptime", sub: "Auto-scaling + failover" },
    ],
  },
  {
    slug: "solar-pv-crm",
    niche: "Cloud Native",
    tag: "Full Stack · Django · AI · CRM",
    title: "Solar PV Installation CRM with AI Email Automation",
    techs: ["django", "python", "postgresql", "redis", "docker", "githubactions", "celery", "plotly", "anthropic", "stripe", "googleads", "facebook", "aws", "sentry"],
    subtitle: "Django · PostgreSQL/PostGIS · Celery · Redis · Claude AI · Stripe · Docker · GitHub Actions",
    diagram: `${process.env.PUBLIC_URL}/projects/solar-pv-crm/architecture.svg`,
    images: [
      `${process.env.PUBLIC_URL}/projects/solar-pv-crm/01.webp`,
      `${process.env.PUBLIC_URL}/projects/solar-pv-crm/02.webp`,
      `${process.env.PUBLIC_URL}/projects/solar-pv-crm/03.webp`,
    ],
    problem: "When you rely on disconnected tools — Eye on Task, Xero, Zapier, email — you lose control over lead data, proposal flow, installation scheduling, and invoicing. Every missed follow-up costs you revenue and customer trust.",
    solution: "Built a complete solar CRM on Django with Claude AI handling 5,000+ emails/month automatically (lead intake, follow-ups, contracts, invoices, aftercare), Stripe payment processing, Plotly/Mapbox heatmaps for geographic targeting, and direct Google/Meta Ads integration. Result: 36% lower CPA, 70% better ROAS.",
    impact: "Production-ready solar CRM replacing Eye on Task, Xero, and Zapier — deployed in 6 weeks. 5,000+ AI-generated emails/month with zero manual composition. €10K-12K total investment vs €12K-24K/year in SaaS costs — €11K-23K saved year 1.",
    implementation: [
      "Django Lead model captures full client details: name, email, phone, address, city, county, property type, roof area, energy consumption.",
      "Lead priority tagging by county/area (High, Medium, Low) enables geographic targeting and service area management.",
      "Cases/Tickets system repurposed as appointment scheduling with installation date, field team assignment, and commissioning form submission.",
      "LocationTracking model records geolocation, county, postal code, and conversion status per lead — feeding geographic analytics.",
      "PostgreSQL + PostGIS enables county-level geographic queries, area clustering, and territory analysis.",
      "Claude API integration auto-generates emails across entire workflow — lead intake, design follow-ups, 7-day proposal reminders, contract acceptance, invoices, aftercare, support tickets.",
      "Proposal generation combines quote data with SurgePV design output into professional 2-page PDFs with sales review → sent → accepted → surveyed workflow.",
      "Invoice automation creates deposit invoices on proposal acceptance and final balance invoices post-installation — sent via email with Stripe payment tracking.",
      "SEAI grant application auto-populates 90% from existing data, reducing paperwork time from 30 minutes to 5 minutes per job.",
      "Installation calendar displays scheduled jobs with field team assignments and mobile commissioning form submission.",
      "Client portal provides document access (contract, invoices, grant status) and support ticket submission with engineer callout booking.",
      "Support ticket inbox with Claude AI-suggested responses, engineer callout scheduling, and ticket lifecycle tracking.",
      "Plotly/Mapbox heatmap displays lead density and conversion rates by county — identifying high-opportunity territories for expansion.",
      "Google Ads and Facebook Ads APIs auto-sync campaign performance, calculate ROI per county, and recommend budget reallocation.",
      "Multi-location support via multi-tenant architecture — manage 1 branch or 10+ with centralized lead pipeline and unified reporting.",
      "Role-based access control (Admin, Sales, Field Team, Office Admin) with per-role dashboards and permissions.",
      "Self-hosted on AWS Ireland with PostgreSQL encryption at rest, HTTPS/TLS, automated daily backups, and disaster recovery.",
      "Docker containerization — single docker compose up command deploys entire stack (API, frontend, database, Redis, Celery, Celery Beat).",
      "GitHub Actions CI/CD with automated tests, staging on push to develop, production on release tags — zero-downtime blue-green deployments.",
      "Git-based infrastructure as code — entire system reproducible from GitHub with single command: git clone → docker compose up.",
    ],
    stats: [
      { value: "5,000+", label: "AI Emails/Month", sub: "Zero manual composition" },
      { value: "36%", label: "Lower CPA", sub: "€50 → €32 per acquisition" },
      { value: "70%", label: "Better ROAS", sub: "2.0x → 3.4x in 60 days" },
      { value: "€11-23K", label: "Saved Year 1", sub: "vs €12-24K/yr SaaS costs" },
    ],
  },
];
