// projects data — separated for maintainability
export const coreProjects = [
  {
    slug: "kubernetes-platform",
    niche: "Platform Engineering",
    tag: "Infrastructure · Platform Engineering · Multi-Cloud",
    title: "Production-Grade Kubernetes Platform",

    subtitle: "AWS · Azure · DigitalOcean · Self-Managed · HA Cluster · Built from Scratch",
    github: "https://github.com/AbdurRehman924/self-managed-k8s-aws",
    githubLabel: "AWS",
    githubAlt: { label: "Azure / DigitalOcean", url: "https://github.com/AbdurRehman924/hipster-shop" },
    source: { text: "Orchestrated 12 microservices based on Google's project: ", link: "Online Boutique", url: "https://github.com/GoogleCloudPlatform/microservices-demo" },
    diagram: `${process.env.PUBLIC_URL}/projects/k8s-platform/architecture.svg`,
    problem: "When your cloud provider manages Kubernetes, you lose control over security, performance, and cost. If something breaks, you're debugging a black box — and every hour of downtime costs you money and trust.",
    solution: "Built self-managed Kubernetes clusters from raw compute across three cloud providers — giving full ownership of every layer with zero reliance on a managed control plane. The result: a portable, auditable platform that runs identically on AWS, Azure, or DigitalOcean.",
    implementation: [
      "Terraform provisions all cloud infrastructure end-to-end.",
      "kubeadm bootstraps the control plane and worker nodes.",
      "Google's 12-microservice Online Boutique runs as the production workload.",
      "Istio enforces mTLS across all service-to-service communication.",
      "ArgoCD drives GitOps deployments.",
      "Falco and Trivy handle runtime and image security.",
      "Prometheus, Grafana, Loki, and Jaeger provide full-stack observability.",
    ],
    impact: "Identical platform running on three cloud providers — proving full portability with zero vendor lock-in. 43 AWS resources provisioned with zero manual steps. 11 of 12 engineering phases complete including service mesh, autoscaling, distributed tracing, and GitOps delivery.",
    stats: [
      { value: "3", label: "Clouds, One Platform", sub: "AWS · Azure · DigitalOcean" },
      { value: "100%", label: "Control Plane Ownership", sub: "No managed black box" },
      { value: "43", label: "Resources, Zero Clicks", sub: "Terraform end-to-end" },
      { value: "12", label: "Services in Production", sub: "Full observability stack" },
    ],
    techStack: [
      "Kubernetes (kubeadm)", "AWS EC2 · VPC · NLB · EBS", "Terraform",
      "Calico CNI", "Istio 1.23.4 + mTLS", "Prometheus + Grafana",
      "Loki + Promtail", "Jaeger", "ArgoCD", "Falco + Trivy",
      "HPA + VPA", "cert-manager", "Velero",
    ],
    phases: [
      { name: "AWS Infrastructure", done: true }, { name: "Cluster Bootstrap", done: true },
      { name: "Microservices Deployment", done: true }, { name: "Ingress & External Access", done: true },
      { name: "Monitoring & Alerting", done: true }, { name: "Security & Compliance", done: true },
      { name: "Centralized Logging", done: true }, { name: "Autoscaling (HPA/VPA)", done: true },
      { name: "GitOps (ArgoCD)", done: true }, { name: "Service Mesh (Istio)", done: true },
      { name: "Distributed Tracing", done: true }, { name: "Backup & DR (Velero)", done: false },
    ],
  },
  {
    slug: "aws-secure-baseline",
    niche: "Security & Compliance",
    tag: "AWS · Security · Infrastructure-as-Code · Multi-Account",
    title: "AWS Secure Baseline — Multi-Account Security Platform",
    subtitle: "GuardDuty · Security Hub · CloudTrail · AWS Config · SCPs · Terraform · GitHub Actions",
    github: "https://github.com/AbdurRehman924/aws-secure-baseline",
    diagram: `${process.env.PUBLIC_URL}/projects/aws-secure-baseline/architecture.svg`,
    problem: "Most AWS environments treat security as an afterthought — enabled in prod but not dev, alerts that nobody checks, and nothing preventing an admin from disabling protections entirely. By the time you fix it, every environment has drifted into a different, un-auditable state.",
    solution: "Built a Terraform-based security platform that provisions the same baseline across every AWS environment on day one — enforced at the organisation level so even an admin with compromised credentials can't disable it. Detection, alerting, and compliance checks run identically everywhere, automatically.",
    implementation: [
      "Two isolated AWS accounts: non-prod (dev/sit) and prod (staging/prod) — blast radius contained by design.",
      "CloudTrail with multi-region logging, S3 data events, Lambda invocations, log file validation, and 9 CIS-aligned CloudWatch alarms for root usage, IAM changes, and security group modifications.",
      "GuardDuty with S3 Protection, Kubernetes Protection, and Malware Protection — HIGH/CRITICAL findings routed to SNS via EventBridge within minutes.",
      "Security Hub running CIS AWS Foundations Benchmark v1.4.0 and AWS Foundational Security Best Practices across all regions, with a finding aggregator for a single-pane view.",
      "30 AWS Config managed rules covering encryption, access control, logging, networking, and compute — non-compliance events trigger SNS alerts automatically.",
      "6 SCPs enforced at the OU level: deny leaving the organisation, deny disabling security services, deny root account usage, restrict to approved regions, block public S3, and require IMDSv2 on all EC2.",
      "GitHub Actions CI/CD via OIDC — no stored credentials. Plan on PR, apply on merge, manual approval gate for prod. tfsec + checkov block HIGH/CRITICAL findings before merge.",
    ],
    impact: "Every environment gets an identical, auditable security baseline from day one — no manual steps, no drift. Security cannot be disabled even by a compromised admin account. Threats are detected in real-time across behavioural anomalies, configuration drift, compliance gaps, and active threats simultaneously.",
    stats: [
      { value: "6", label: "SCPs, Zero Overrides", sub: "Enforced above IAM" },
      { value: "30", label: "Config Rules", sub: "Encryption · IAM · Network · Compute" },
      { value: "9", label: "CIS Alarms", sub: "Real-time on critical API calls" },
      { value: "4", label: "Environments, One Baseline", sub: "dev · sit · staging · prod" },
    ],
    techStack: [
      "Terraform", "AWS Organizations + SCPs",
      "GuardDuty (S3 · K8s · Malware Protection)", "Security Hub (CIS v1.4 · AFSBP)",
      "CloudTrail (multi-region · Insights)", "AWS Config (30 rules)",
      "KMS (per-service keys)", "EventBridge + SNS",
      "GitHub Actions (OIDC)", "tfsec + checkov",
      "S3 + DynamoDB (remote state)", "CloudFront + WAF",
    ],
    phases: [
      { name: "Bootstrap (S3 state + DynamoDB lock)", done: true },
      { name: "Global IAM (OIDC for GitHub Actions)", done: true },
      { name: "CloudTrail Module", done: true },
      { name: "GuardDuty Module", done: true },
      { name: "Security Hub Module", done: true },
      { name: "AWS Config Module (30 rules)", done: true },
      { name: "SCPs Module (6 policies)", done: true },
      { name: "Multi-account environments", done: true },
      { name: "CI/CD (plan · apply · security scan)", done: true },
      { name: "Route53 + Global DNS", done: true },
    ],
  },
  {
    slug: "secure-supply-chain",
    niche: "Supply Chain Security",
    tag: "Supply Chain Security · GitOps · Platform Engineering",
    title: "End-to-End Secure Software Supply Chain",
    subtitle: "Cosign Keyless · SLSA L2 · Kyverno · Falco · ArgoCD · SBOM · Distroless",
    github: "https://github.com/AbdurRehman924/secure-supply-chain",
    diagram: `${process.env.PUBLIC_URL}/projects/secure-supply-chain/architecture.svg`,
    problem: "You can't prove that what's running in production is exactly what was built and approved. A tampered image can slip through a standard pipeline — and you'd have no way to know until it's too late.",
    solution: "Designed a three-layer enforcement chain: every artifact is signed the moment it's built, verified before it's deployed, and monitored while it runs. No signing keys to manage — OIDC handles authentication automatically. If an image isn't signed, it never reaches a running pod.",
    implementation: [
      "GitHub Actions CI executes dual vulnerability scanning (Trivy + Grype).",
      "Syft generates an SBOM, attested to the image via Cosign.",
      "The SLSA GitHub Generator produces L2 provenance using an isolated signing job.",
      "The digest is pinned in the GitOps repository — no mutable tags.",
      "ArgoCD syncs exclusively from the pinned digest.",
      "Kyverno verifyImages policy enforces all three attestations at admission time before any pod is scheduled.",
    ],
    impact: "Every piece of code is cryptographically traceable from the commit that wrote it to the pod running it. Zero unsigned images make it to production. Zero signing keys to store, rotate, or leak — OIDC eliminates key management entirely.",
    stats: [
      { value: "3", label: "Enforcement Layers", sub: "Nothing slips through" },
      { value: "0", label: "Stored Signing Keys", sub: "Keyless OIDC only" },
      { value: "0", label: "Mutable Tags in Prod", sub: "Digest-pinned, always" },
      { value: "SLSA L2", label: "Provenance on Every Build", sub: "Commit → pod, traceable" },
    ],
    techStack: [
      "Cosign (Keyless OIDC)", "SLSA GitHub Generator", "Syft (SBOM)",
      "Trivy + Grype (dual scanning)", "Kyverno (verifyImages)",
      "Falco (runtime rules)", "ArgoCD", "Kustomize",
      "GitHub Actions", "GHCR (digest-pinned)", "Distroless (Go)",
    ],
    phases: [
      { name: "Multi-stage Distroless Build", done: true },
      { name: "Trivy + Grype Scanning", done: true },
      { name: "Syft SBOM + Cosign Attest", done: true },
      { name: "Cosign Keyless Signing", done: true },
      { name: "SLSA L2 Provenance", done: true },
      { name: "Digest Pinning in GitOps", done: true },
      { name: "Kyverno verifyImages Policy", done: true },
      { name: "Falco Runtime Rules", done: true },
      { name: "ArgoCD AppProject RBAC", done: true },
      { name: "PSS Restricted + No :latest", done: true },
    ],
  },
  {
    slug: "azure-opa-pipeline",
    niche: "Policy-as-Code",
    tag: "Azure · DevOps · Policy-as-Code",
    title: "Azure DevOps Pipeline with OPA Policy Enforcement",
    subtitle: "AKS · ACR · GitHub Actions · Ansible · Open Policy Agent",
    github: "https://github.com/AbdurRehman924/Portfolio-Devops",
    diagram: `${process.env.PUBLIC_URL}/projects/portfolio-devops/architecture.svg`,
    problem: "Bad configurations — open access, missing encryption, untagged resources — reach production before anyone notices. Manual reviews don't catch everything and don't scale. By the time you find the problem, it's already costing you.",
    solution: "Wrote policy-as-code rules that evaluate every infrastructure change before it's applied — blocking non-compliant configurations at the source. Four parallel pipelines (infrastructure, app, config, security) execute from a single git push with zero manual gates.",
    implementation: [
      "Terraform provisions AKS, ACR, Key Vault, and VNet on Azure.",
      "OPA policies enforce no-public-AKS and mandatory resource tagging at plan time — violations fail the pipeline before apply.",
      "Ansible configures the bastion host post-provisioning.",
      "GitHub Actions orchestrates all four pipelines in parallel.",
      "The security pipeline runs Trivy image scanning independently.",
    ],
    impact: "Zero non-compliant resources reach production. Violations caught at plan time, not after deployment. Four parallel pipelines cut delivery time. Zero manual steps from commit to running on AKS.",
    stats: [
      { value: "0", label: "Bad Configs Reach Azure", sub: "Blocked at plan time" },
      { value: "4", label: "Pipelines, One Git Push", sub: "Infra · App · Config · Security" },
      { value: "5", label: "Azure Services Wired Up", sub: "AKS · ACR · KV · VNet · VM" },
      { value: "0", label: "Manual Steps", sub: "Commit to running workload" },
    ],
    techStack: [
      "Azure AKS", "Azure ACR", "Azure Key Vault", "Terraform (Azure)",
      "GitHub Actions", "Open Policy Agent (OPA)", "Ansible",
      "Docker · Nginx", "Kubernetes", "React 18 · Tailwind CSS",
    ],
    phases: [
      { name: "Azure Infrastructure (Terraform)", done: true },
      { name: "OPA Policy Enforcement", done: true },
      { name: "Docker Multi-Stage Build", done: true },
      { name: "ACR Image Push", done: true },
      { name: "AKS Deployment", done: true },
      { name: "Ansible Bastion Config", done: true },
      { name: "Security Scanning Pipeline", done: true },
      { name: "Monitoring (Node Exporter)", done: true },
    ],
  },
  {
    slug: "gitops-sealed-secrets",
    niche: "GitOps & Security",
    tag: "Azure · GitOps · Secret Management",
    title: "Multi-Environment GitOps Platform with Sealed Secrets",
    subtitle: "K3s on Azure · ArgoCD · Helm · Sealed Secrets · Dev/Staging/Prod",
    github: "https://github.com/AbdurRehman924/DevSecOps-Platform",
    diagram: `${process.env.PUBLIC_URL}/projects/devsecops-platform/architecture.svg`,
    problem: "Storing passwords and API keys in Git is a security risk. Leaving them out breaks the GitOps model where everything should be version-controlled and auditable. Most teams accept the tradeoff — I found a way to get both.",
    solution: "Implemented Sealed Secrets — secrets are encrypted before they ever touch Git, and only the in-cluster controller holds the decryption key. Plaintext credentials never exist outside the cluster boundary, while the full GitOps model (version control, audit trail, auto-sync) is preserved end-to-end.",
    implementation: [
      "Terraform provisions a K3s VM on Azure.",
      "ArgoCD manages three environment overlays (dev/staging/prod) via Kustomize.",
      "Each environment is isolated by namespace and RBAC.",
      "GitHub Actions builds and scans images with Trivy before pushing to Docker Hub.",
      "A Helm chart packages the application for consistent cross-environment deployments.",
    ],
    impact: "Zero plaintext secrets in Git. Three fully isolated environments managed from a single repository with automatic sync and self-healing — configuration drift is eliminated entirely.",
    stats: [
      { value: "0", label: "Plaintext Secrets in Git", sub: "Encrypted before commit" },
      { value: "3", label: "Environments, One Repo", sub: "dev · staging · prod" },
      { value: "0", label: "Config Drift", sub: "ArgoCD self-heals always" },
      { value: "100%", label: "GitOps Model Preserved", sub: "Security + auditability" },
    ],
    techStack: [
      "K3s (Azure VM)", "Terraform (Azure)", "ArgoCD",
      "Sealed Secrets (Bitnami)", "Helm", "Kustomize (dev/staging/prod)",
      "GitHub Actions", "Trivy", "Docker Hub", "Docker · Nginx",
    ],
    phases: [
      { name: "Azure K3s VM (Terraform)", done: true },
      { name: "ArgoCD Installation", done: true },
      { name: "Sealed Secrets Setup", done: true },
      { name: "Helm Chart", done: true },
      { name: "Dev Overlay (Kustomize)", done: true },
      { name: "Staging Overlay", done: true },
      { name: "Prod Overlay", done: true },
      { name: "CI Pipeline (Trivy scan)", done: true },
    ],
  },
];
