export const techNames = {
  // Core tools
  kubernetes: "Kubernetes", terraform: "Terraform", aws: "AWS", azure: "Azure",
  digitalocean: "DigitalOcean", istio: "Istio", argo: "ArgoCD",
  prometheus: "Prometheus", grafana: "Grafana", falco: "Falco", trivy: "Trivy",
  calico: "Calico", jaeger: "Jaeger", velero: "Velero", docker: "Docker",
  githubactions: "GitHub Actions", helm: "Helm", amazonwebservices: "AWS",
  cloudflare: "Cloudflare", kustomize: "Kustomize", go: "Go",
  cosign: "Cosign", kyverno: "Kyverno", microsoftazure: "Azure",
  openpolicyagent: "OPA",   nginx: "Nginx", mysql: "MySQL", paypal: "PayPal", ansible: "Ansible", k3s: "K3s",
  algolia: "Algolia", mapbox: "Mapbox",
  nuxt: "Nuxt.js", strapi: "Strapi", tailwindcss: "Tailwind CSS",
  cloudflareworkers: "Cloudflare Workers", vuedotjs: "Vue.js", unocss: "UnoCSS",
  magento: "Magento", graphql: "GraphQL", firebase: "Firebase", stripe: "Stripe",
  django: "Django", python: "Python", postgresql: "PostgreSQL", redis: "Redis",
  celery: "Celery", googleads: "Google Ads", facebook: "Facebook",
  plotly: "Plotly", anthropic: "Anthropic",
  googleappsscript: "Google Apps Script",
  oracle: "Oracle Cloud",
  sqlite: "SQLite",
  telegram: "Telegram",
  googlesheets: "Google Sheets",
  react: "React",
  nextdotjs: "Next.js",
  javascript: "JavaScript",
  typescript: "TypeScript",
  nodedotjs: "Node.js",
  express: "Express",
  mongodb: "MongoDB",
  rabbitmq: "RabbitMQ",
  // AWS services
  amazonec2: "EC2",
  amazons3: "S3",
  amazonrds: "RDS",
  amazondynamodb: "DynamoDB",
  amazoncloudwatch: "CloudWatch",
  amazoncloudfront: "CloudFront",
  amazonroute53: "Route 53",
  amazonguardduty: "GuardDuty",
  amazoneks: "EKS",
  amazonvpc: "VPC",
  amazonsns: "SNS",
  amazoneventbridge: "EventBridge",
  awsiam: "IAM",
  awskms: "KMS",
  awscloudtrail: "CloudTrail",
  awsconfig: "AWS Config",
  awssecurityhub: "Security Hub",
  awsorganizations: "AWS Organizations",
  awswaf: "WAF",
  awsnlb: "NLB",
  awsnatgateway: "NAT Gateway",
  bastion: "Bastion Host",
  // Azure services
  azureaks: "AKS",
  azureacr: "ACR",
  azurekeyvault: "Key Vault",
  azurevnet: "VNet",
  azurevm: "Azure VM",
  terraformcloud: "Terraform Cloud",
  // OCI services
  ocivcn: "OCI VCN",
  ocicompute: "OCI Compute",
  ocigateway: "Internet Gateway",
  openvpn: "OpenVPN",
  // Supply chain / security tools
  ghcr: "GHCR",
  sigstore: "Sigstore",
  slsa: "SLSA",
  grype: "Grype",
  syft: "Syft",
};

const iconFiles = {
  // Core tools
  kubernetes:"kubernetes.svg", terraform:"terraform.svg", digitalocean:"digitalocean.svg",
  istio:"istio.svg", argo:"argo.svg", prometheus:"prometheus.svg", grafana:"grafana.svg",
  falco:"falco.svg", trivy:"trivy.svg", jaeger:"jaeger.svg", docker:"docker.svg",
  githubactions:"githubactions.svg", helm:"helm.svg", go:"go.svg", nginx:"nginx.svg", mysql:"mysql.svg", paypal:"paypal.svg",
  ansible:"ansible.svg", k3s:"k3s.svg", nuxt:"nuxt.svg", strapi:"strapi.svg",
  unocss:"unocss.svg", vuedotjs:"vuedotjs.svg", cloudflare:"cloudflare.svg",
  cloudflareworkers:"cloudflareworkers.svg", firebase:"firebase.svg",
  tailwindcss:"tailwindcss.svg", graphql:"graphql.svg", stripe:"stripe.svg",
  aws:"aws.svg", azure:"azure.svg", amazonwebservices:"amazonwebservices.svg",
  microsoftazure:"microsoftazure.svg", magento:"magento.svg", cosign:"cosign.svg",
  openpolicyagent:"openpolicyagent.svg", calico:"calico.svg", velero:"velero.svg",
  kyverno:"kyverno.svg", kustomize:"kustomize.svg",
  django:"django.svg", python:"python.svg", postgresql:"postgresql.svg",
  redis:"redis.svg", celery:"celery.svg", googleads:"googleads.svg", facebook:"facebook.svg",
  plotly:"plotly.svg", anthropic:"anthropic.svg", sentry:"sentry.svg",
  googleappsscript:"googleappsscript.svg", oracle:"oracle.svg",
  sqlite:"sqlite.svg", telegram:"telegram.svg", googlesheets:"googlesheets.svg",
  react:"react.svg", nextdotjs:"nextdotjs.svg", javascript:"javascript.svg",
  typescript:"typescript.svg", nodedotjs:"nodedotjs.svg", express:"express.svg",
  mongodb:"mongodb.svg", rabbitmq:"rabbitmq.svg",
  algolia:"algolia.svg", mapbox:"mapbox.svg",
  // AWS services
  amazonec2:"amazonec2.svg",
  amazons3:"amazons3.svg",
  amazonrds:"amazonrds.svg",
  amazondynamodb:"amazondynamodb.svg",
  amazoncloudwatch:"amazoncloudwatch.svg",
  amazoncloudfront:"amazoncloudfront.svg",
  amazonroute53:"amazonroute53.svg",
  amazonguardduty:"amazonguardduty.svg",
  amazoneks:"amazoneks.svg",
  amazonvpc:"amazonvpc.svg",
  amazonsns:"amazonsns.svg",
  amazoneventbridge:"amazoneventbridge.svg",
  awsiam:"awsiam.svg",
  awskms:"awskms.svg",
  awscloudtrail:"awscloudtrail.svg",
  awsconfig:"awsconfig.svg",
  awssecurityhub:"awssecurityhub.svg",
  awsorganizations:"awsorganizations.svg",
  awswaf:"awswaf.svg",
  awsnlb:"awsnlb.svg",
  awsnatgateway:"awsnatgateway.svg",
  bastion:"bastion.svg",
  // Azure services
  azureaks:"azureaks.svg",
  azureacr:"azureacr.svg",
  azurekeyvault:"azurekeyvault.svg",
  azurevnet:"azurevnet.svg",
  azurevm:"azurevm.svg",
  terraformcloud:"terraformcloud.svg",
  // OCI services
  ocivcn:"ocivcn.svg",
  ocicompute:"ocicompute.svg",
  ocigateway:"ocigateway.svg",
  openvpn:"openvpn.svg",
  // Supply chain / security tools
  ghcr:"ghcr.svg",
  sigstore:"sigstore.svg",
  slsa:"slsa.svg",
  grype:"grype.svg",
  syft:"syft.svg",
};

export const iconUrl = (tech) => {
  const file = iconFiles[tech];
  if (file) return `${process.env.PUBLIC_URL}/icons/${file}`;
  return null;
};